### ISSUE TITLE
Adding funcs

### ISSUE THREAD

**Issue by 7eith** [ripZeide/Troll_42#2]
* Refresh ZSH after installed Brew (brew n’existe pas, donc il ne peut pas installer le switch audio et le lancer parcontre la seconde fois ou j’troll le mec ça marche niquel)
* Auto switch audio (when ls or anything else audio switch to 100 and set output to default)
* Refresh all iTerms instances (need to zsh to reapply)
* Hide more (alias custom if oh my zsh) 
* Remap volume key (disable and set max) 

* Adding spam_troll (lock screen and spam sound like John Cena)
* Adding sound: Arouf partout meme dans ton trou, Jeanne au secours, rire de kameto, hurlement de corobizar ou phrases du goat sardoche

**Comment by cgarrot** [comment]
Ça va être add mais pas tout suite 🙄

**Comment by 7eith** [comment]
#3 all except all sound, remap volume key (instead just spam and set sound in while 7 times max), except refresh iterm instance (how? )
